### ISSUE TITLE
Multiple github.com accounts

### ISSUE THREAD

**Issue by chrisnicholson** [savaryna/git-add-account#13]
Hi @savaryna, great little utility you've created. I'm curious about my experience trying to connect to GitHub.com twice with different accounts. I had to make some modifications to the ssh config file which appears to work, but I'm curious if it was necessary (possibly I set things up wrong?) and if necessary, is it the right way to go about it. I've written up my steps here https://github.com/chrisnicholson/git-add-account#%EF%B8%8F-possible-next-steps.

**Comment by savaryna** [comment]
Hi @chrisnicholson, sorry for the late reply, I think it should just work as long as you use **separate** working directories.

If you could guide me through what you have tried maybe I can help you. Or if possible, attach the contents of `~/.ssh/config` and `~/.gitconfig` with any sensitive data edited out ofc. Thanks!
