### ISSUE TITLE
SSH Key Addition Enhancement

### ISSUE THREAD

**Issue by jesusberrio122** [savaryna/git-add-account#15]
After adding a new account, I encountered an unexpected issue when working with Git. I assumed that the package would automatically add SSH keys for the new account, but this was not the case. As a result, I spent a considerable amount of time troubleshooting Git clone operations.

**Expected Behavior:**
I expected the SSH keys to be added automatically when adding a new account, simplifying the process of working with Git repositories associated with that account.
Example: 
`     ssh-add -K ~/.ssh/github-rahul-office
`

**Actual Behavior:**
The SSH keys were not added automatically, causing issues during Git clone operations. I had to manually run the `ssh-add` command to add the keys, which was not initially clear to me.

**Suggested Enhancement:**
I propose enhancing the package to automatically add SSH keys when a new account is added. This would improve the user experience and prevent confusion for users who may not be familiar with the manual process of adding SSH keys.

**Steps to Reproduce:**
1. Add a new account.
2. Attempt to clone a Git repository associated with the new account.
3. Encounter issues due to SSH keys not being added automatically.

**Additional Information:**
- Operating System: [macOS 13.3.1]
- Package Version: [1.0.2]

Please consider implementing this enhancement to streamline the user experience and prevent potential issues for users. Thank you!

**Comment by savaryna** [comment]
Hi @jesusberrio122, the keys should be automatically added on the first run (git command). Can you guide me through the steps to reproduce this issue? Maybe you can post what input did you provide for the prompts or a copy of `~/.ssh/config` and `~/.gitconfig` with any sensitive data edited out ofc. I see you said on point 2 "Attempt to clone a Git repository associated with the new account.", was the attempt to clone made from the working directory chosen during setup or someplace else?
