### ISSUE TITLE
Error when pushing to remote repository

### ISSUE THREAD

**Issue by boklanov** [savaryna/git-add-account#7]
Hi there, I’m a big fan of your git-add-account tool. It’s very useful for managing multiple GitHub accounts! However, I’m facing a problem when I try to push to a remote repository. I get this error:
```
octrow@DESKTOP-1P77K52:~/Dev/homework_bot$ git push
Warning: Identity file /home/octrow/.ssh/github-octrow not accessible: No such file or directory.
ssh: Could not resolve hostname github.com-octrow: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I checked that the configuration and key files exist.
I’m not sure what is causing this error and how to fix it. Can you please help me? I really appreciate your work and your support. Thank you very much.😊
P.S. I’m using Ubuntu 22.04.2 LTS through WSL2 Windows 11 using vscode.

**Comment by boklanov** [comment]
> Hi there, I’m a big fan of your git-add-account tool. It’s very useful for managing multiple GitHub accounts! However, I’m facing a problem when I try to push to a remote repository. I get this error:
> 
> ```
> octrow@DESKTOP-1P77K52:~/Dev/homework_bot$ git push
> Warning: Identity file /home/octrow/.ssh/github-octrow not accessible: No such file or directory.
> ssh: Could not resolve hostname github.com-octrow: Name or service not known
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> I checked that the configuration and key files exist. I’m not sure what is causing this error and how to fix it. Can you please help me? I really appreciate your work and your support. Thank you very much.😊 P.S. I’m using Ubuntu 22.04.2 LTS through WSL2 Windows 11 using vscode.

I'm not sure what the problem was, now connecting to github in standard mode works. I suspect the problem was in the ssh-agent, specifically `The authenticity of host 'github.com (140.82.121.4)' can't be established.` and part of the solution: `ssh-keyscan github.com >> ~/.ssh/known_hosts'

**Comment by savaryna** [comment]
@boklanov Is it possible that you answered `no` when you run the command the first time and was asked to include the host in known hosts?

**Comment by savaryna** [comment]
Will close this one due to no response.

**Comment by savaryna** [comment]
Will close this one due to no response.
